---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: cluster-api
  app.kubernetes.io/name: cluster-api
  app.kubernetes.io/instance: '{{ .Release.Name }}'
fieldSpecs:
  - path: metadata/labels
    create: true
