name: cluster-api

hooks:
  images:
    domain: quay.io

images:
  domain: registry.k8s.io
  core:
    name: cluster-api/cluster-api-controller
  bootstrap:
    name: cluster-api/kubeadm-bootstrap-controller
  controlplane:
    name: cluster-api/kubeadm-control-plane-controller
  tag: v1.3.5

watchFilter: capi

# We install CRDs through a Job with the helm specific crd folder.
crds:
  install: true
